### Read hits

In [1]:
import csv
import pandas as pd

In [2]:
dataset = pd.read_csv('event000001000/event000001000-hits.csv')

In [3]:
print(dataset)

        hit_id         x          y       z  volume_id  layer_id  module_id
0            1  -64.4099  -7.163700 -1502.5          7         2          1
1            2  -55.3361   0.635342 -1502.5          7         2          1
2            3  -83.8305  -1.143010 -1502.5          7         2          1
3            4  -96.1091  -8.241030 -1502.5          7         2          1
4            5  -62.6736  -9.371200 -1502.5          7         2          1
...        ...       ...        ...     ...        ...       ...        ...
120934  120935 -763.8630  51.569400  2944.5         18        12         97
120935  120936 -808.7050   3.459260  2944.5         18        12         97
120936  120937 -982.9360  41.460900  2952.5         18        12         98
120937  120938 -942.6990  18.489100  2952.5         18        12         98
120938  120939 -922.8900   2.092850  2952.5         18        12         98

[120939 rows x 7 columns]

In [6]:
dataset_1 = pd.read_csv('event000001000/sel/event000001000-truth-wo-noise-sel-01.csv')
dataset_1.head()

,hit_id,particle_id,tx,ty,tz,tpx,tpy,tpz,weight
0,46135,4512601878822912,-39.49650,-8.13864,598.0,-1.180050,-0.255313,17.92720,0.000027
1,47693,4521879008182272,29.78220,5.70260,598.0,0.300576,0.049156,6.00683,0.000010
2,47696,4510540294520832,54.45050,19.16760,598.0,0.676876,0.219899,7.37756,0.000016
3,48281,4535210586669056,2.17646,50.50150,598.0,0.001249,0.442641,5.28081,0.000011
4,48297,4515556816322560,4.15659,52.74050,598.0,0.006444,0.249950,2.83779,0.000012

In [8]:
hit_id_list = []
for i in range(dataset_1.shape[0]):
    hit_id_list.append(dataset_1['hit_id'][i])
hit_id_list[:10]

[46135, 47693, 47696, 48281, 48297, 48887, 49200, 50667, 50685, 51268]

In [14]:
#dataset[dataset['hit_id'].isin([dataset_1['hit_id'][0], dataset_1['hit_id'][1]])]
dataset_2 = dataset[dataset['hit_id'].isin(hit_id_list)]
list(set(dataset_2['z']))

{598.0, 698.0, 818.0, 958.0, 1098.0, 1298.0, 1498.0}

### ... and correct by leaving only volume_id = 9 (look at the z values) !!!

In [15]:
# z_list = [598.0, 698.0, 818.0, 958.0, 1098.0, 1298.0, 1498.0]
z_list = list(set(dataset_2['z']))

In [16]:
dataset_3 = dataset_2[dataset_2['z'].isin(z_list)]
dataset_3.shape

(42, 7)

In [59]:
dataset_3.to_csv('event000001000/event000001000-hits-sel-01.csv', index=False)

In [60]:
dataset_4 = dataset_1[dataset_1['tz'].isin(z_list)]
dataset_4

,hit_id,particle_id,tx,ty,tz,tpx,tpy,tpz,weight
0,46135,4512601878822912,-39.496500,-8.13864,598.0,-1.180050,-0.255313,17.92720,0.000027
2,47693,4521879008182272,29.782200,5.70260,598.0,0.300576,0.049156,6.00683,0.000010
3,47696,4510540294520832,54.450500,19.16760,598.0,0.676876,0.219899,7.37756,0.000016
5,48281,4535210586669056,2.176460,50.50150,598.0,0.001249,0.442641,5.28081,0.000011
6,48297,4515556816322560,4.156590,52.74050,598.0,0.006444,0.249950,2.83779,0.000012
9,48887,4504080663707648,-55.429800,27.96600,598.0,-0.577502,0.270107,6.16600,0.000012
10,49200,4512601878822912,-46.074600,-9.56755,698.0,-1.178860,-0.257737,17.92660,0.000015
11,50667,4521879008182272,34.780300,6.50040,698.0,0.300963,0.047006,6.00625,0.000008
12,50685,4510540294520832,63.670900,22.09860,698.0,0.681317,0.214104,7.37670,0.000011
15,51268,4515556816322560,4.331950,61.51950,698.0,0.002427,0.248342,2.83734,0.000007
16,51298,4535210586669056,2.159900,58.86430,698.0,-0.002731,0.441244,5.28027,0.000008
18,51900,4504080663707648,-64.819300,32.25880,698.0,-0.579965,0.262001,6.16555,0.000008
19,52216,4512601878822912,-53.977700,-11.29400,818.0,-1.180070,-0.260281,17.92540,0.000010
20,53693,4521879008182272,40.822900,7.43627,818.0,0.302769,0.045925,6.00544,0.000005
21,53705,4510540294520832,74.767200,25.51190,818.0,0.682669,0.207370,7.37516,0.000008
23,54277,4515556816322560,4.406670,72.18910,818.0,-0.001231,0.252519,2.83639,0.000006
24,54289,4535210586669056,2.031080,68.92050,818.0,-0.008784,0.442391,5.27959,0.000006
26,54882,4504080663707648,-76.122000,37.24430,818.0,-0.581414,0.251821,6.16528,0.000006
27,55194,4512601878822912,-63.175000,-13.33830,958.0,-1.176120,-0.264090,17.92510,0.000008
28,56473,4521879008182272,47.935000,8.45989,958.0,0.305082,0.042265,6.00453,0.000003
29,56495,4510540294520832,87.734900,29.39730,958.0,0.683541,0.201367,7.37448,0.000005
31,56943,4535210586669056,1.757550,80.62790,958.0,-0.012764,0.441512,5.27893,0.000004
32,56962,4515556816322560,4.100580,84.68260,958.0,-0.009477,0.252363,2.83590,0.000005
34,57480,4504080663707648,-89.354500,42.95250,958.0,-0.583508,0.247995,6.16465,0.000004
35,57731,4512601878822912,-72.348200,-15.41630,1098.0,-1.173540,-0.268635,17.92440,0.000011
36,58814,4521879008182272,55.057700,9.39800,1098.0,0.305490,0.039040,6.00069,0.000003
37,58876,4510540294520832,100.740000,33.16350,1098.0,0.684816,0.194858,7.37314,0.000005
38,59240,4515556816322560,3.434410,97.19620,1098.0,-0.016220,0.252883,2.83535,0.000003
39,59242,4535210586669056,1.402470,92.33440,1098.0,-0.015174,0.440805,5.27841,0.000003
41,59691,4504080663707648,-102.592000,48.49940,1098.0,-0.583313,0.240368,6.16448,0.000004
42,59913,4512601878822912,-85.419800,-18.46630,1298.0,-1.169600,-0.277035,17.92310,0.000014
43,60799,4521879008182272,65.173600,10.66580,1298.0,0.303366,0.037112,6.00016,0.000004
44,60847,4510540294520832,119.289000,38.32910,1298.0,0.684524,0.187335,7.37269,0.000005
47,61201,4535210586669056,0.577684,108.97100,1298.0,-0.025609,0.437191,5.27820,0.000003
48,61204,4515556816322560,1.929960,114.92900,1298.0,-0.025011,0.249523,2.83500,0.000003
49,61546,4504080663707648,-121.598000,56.13880,1298.0,-0.586646,0.230126,6.16390,0.000004
50,61752,4512601878822912,-98.447200,-21.59930,1498.0,-1.165840,-0.284349,17.92270,0.000016
51,62502,4521879008182272,75.256700,11.92780,1498.0,0.302176,0.035834,5.99958,0.000005
52,62545,4510540294520832,137.900000,43.33380,1498.0,0.686449,0.181443,7.37195,0.000007
55,62846,4515556816322560,0.083350,132.35300,1498.0,-0.029025,0.245145,2.83471,0.000003
56,62853,4535210586669056,-0.431888,125.57000,1498.0,-0.029203,0.436576,5.27768,0.000005
57,63129,4504080663707648,-140.546000,63.37230,1498.0,-0.584875,0.218040,6.16403,0.000006

In [61]:
dataset_4.to_csv('event000001000/event000001000-truth-wo-noise-sel-01.csv', index=False)

In [31]:
dataset = pd.read_csv('event000001000/event000001000-hits.csv')
dataset.shape

(120939, 7)

In [25]:
dataset_1 = pd.read_csv('event000001000/event000001000-truth-wo-noise.csv')
dataset_1.head()

,hit_id,particle_id,tx,ty,tz,tpx,tpy,tpz,weight
0,2,22525763437723648,-55.3385,0.630805,-1502.5,-0.570605,0.028390,-15.49220,0.000010
1,4,297237712845406208,-96.1229,-8.230360,-1502.5,-0.225235,-0.050968,-3.70232,0.000008
2,5,418835796137607168,-62.6594,-9.375040,-1502.5,-0.281806,-0.023487,-6.57318,0.000009
3,6,108087696726949888,-57.0856,-8.189710,-1502.5,-0.401129,-0.035276,-10.46690,0.000008
4,7,968286151951515648,-73.8608,-2.575860,-1502.5,-0.442662,-0.036969,-9.13010,0.000007

In [29]:
hit_id_truth_wo_noise_list = dataset_1['hit_id'].tolist()
len(hit_id_truth_wo_noise_list)

103305

In [21]:
volume_id = 9
hits_volume = dataset[['volume_id']==volume_id]
hits_volume

       hit_id         x          y       z  volume_id  layer_id  module_id
46045   46046  -68.4571  -4.710600   602.5          9         2          1
46046   46047  -50.8023  -7.835060   602.5          9         2          1
46047   46048  -91.6286   0.788329   602.5          9         2          1
46048   46049  -50.6245   1.708320   602.5          9         2          1
46049   46050  -36.2013  -2.322480   602.5          9         2          1
...       ...       ...        ...     ...        ...       ...        ...
63226   63227 -175.7640   4.273390  1498.0          9        14        108
63227   63228 -151.4340  13.833500  1498.0          9        14        108
63228   63229 -106.5870  -3.005650  1498.0          9        14        108
63229   63230 -160.4430  14.750600  1498.0          9        14        108
63230   63231 -108.0150  10.374600  1498.0          9        14        108

[17186 rows x 7 columns]

In [32]:
dataset_2 = hits_volume[hits_volume['hit_id'].isin(hit_id_truth_wo_noise_list)]
dataset_2

       hit_id         x          y       z  volume_id  layer_id  module_id
46045   46046  -68.4571  -4.710600   602.5          9         2          1
46046   46047  -50.8023  -7.835060   602.5          9         2          1
46047   46048  -91.6286   0.788329   602.5          9         2          1
46048   46049  -50.6245   1.708320   602.5          9         2          1
46049   46050  -36.2013  -2.322480   602.5          9         2          1
...       ...       ...        ...     ...        ...       ...        ...
63225   63226 -122.9710  12.717800  1498.0          9        14        108
63227   63228 -151.4340  13.833500  1498.0          9        14        108
63228   63229 -106.5870  -3.005650  1498.0          9        14        108
63229   63230 -160.4430  14.750600  1498.0          9        14        108
63230   63231 -108.0150  10.374600  1498.0          9        14        108

[16411 rows x 7 columns]

In [42]:
sublayer_2 = list(set(dataset_2['z']))[1::4]
len(sublayer_2)

7

In [46]:
dataset_3 = dataset_2[dataset_2['z'].isin(sublayer_2)]
dataset_3

       hit_id        x         y       z  volume_id  layer_id  module_id
46116   46117 -111.575 -12.45930   598.0          9         2          3
46117   46118 -102.945 -18.67670   598.0          9         2          3
46118   46119 -108.234 -10.83210   598.0          9         2          3
46119   46120 -112.229  -7.95649   598.0          9         2          3
46120   46121 -119.432 -13.30280   598.0          9         2          3
...       ...      ...       ...     ...        ...       ...        ...
63225   63226 -122.971  12.71780  1498.0          9        14        108
63227   63228 -151.434  13.83350  1498.0          9        14        108
63228   63229 -106.587  -3.00565  1498.0          9        14        108
63229   63230 -160.443  14.75060  1498.0          9        14        108
63230   63231 -108.015  10.37460  1498.0          9        14        108

[4979 rows x 7 columns]

In [50]:
truth_particle_id = list(dataset_1[dataset_1['hit_id'].isin(dataset_3['hit_id'].tolist())]['particle_id'])

In [54]:
dataset_3['particle_id'] = truth_particle_id
dataset_3.head()

/var/folders/gk/3j6c_tp12vs48rssjd3prq_c0000gn/T/ipykernel_39176/1356150452.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_3['particle_id'] = truth_particle_id

,hit_id,x,y,z,volume_id,layer_id,module_id,particle_id
46116,46117,-111.575,-12.45930,598.0,9,2,3,333267334498091008
46117,46118,-102.945,-18.67670,598.0,9,2,3,860203196868460544
46118,46119,-108.234,-10.83210,598.0,9,2,3,49542963155435520
46119,46120,-112.229,-7.95649,598.0,9,2,3,274723769157681152
46120,46121,-119.432,-13.30280,598.0,9,2,3,157626261835874304

In [61]:
seclect = list(set(truth_particle_id))[:20]

In [62]:
dataset_4 = dataset_3[dataset_3['particle_id'].isin(seclect)]
dataset_4

,hit_id,x,y,z,volume_id,layer_id,module_id,particle_id
46116,46117,-111.5750,-12.45930,598.0,9,2,3,333267334498091008
46117,46118,-102.9450,-18.67670,598.0,9,2,3,860203196868460544
46118,46119,-108.2340,-10.83210,598.0,9,2,3,49542963155435520
46119,46120,-112.2290,-7.95649,598.0,9,2,3,274723769157681152
46120,46121,-119.4320,-13.30280,598.0,9,2,3,157626261835874304
46121,46122,-119.4630,-12.14600,598.0,9,2,3,598981636658298880
46122,46123,-167.2620,-24.56880,598.0,9,2,3,702562710100901888
46123,46124,-120.3530,-14.74470,598.0,9,2,3,211693577900654592
46124,46125,-140.8570,-22.80400,598.0,9,2,3,702566283513692160
46125,46126,-129.7440,-16.45780,598.0,9,2,3,702565665038401536
46126,46127,-115.6360,-23.17310,598.0,9,2,3,391821620076871680
46127,46128,-44.1703,-13.56100,598.0,9,2,4,707069951860539392
46128,46129,-44.2751,-18.16270,598.0,9,2,4,216178348391399424
46129,46130,-30.5843,-4.12885,598.0,9,2,4,63055067707604992
46130,46131,-50.4222,-7.76025,598.0,9,2,4,873709941301444608
46131,46132,-35.5668,-15.50640,598.0,9,2,4,103593374228938752
47079,47080,33.6450,-46.53040,598.0,9,2,36,711568947282968576
47085,47086,44.7940,-84.72390,598.0,9,2,36,94586724730011648
47109,47110,68.1115,-96.53420,598.0,9,2,38,324259379329105920
47380,47381,40.6160,-23.77810,598.0,9,2,47,585468157716594688
49060,49061,-59.1996,-8.34547,702.5,9,4,1,873709941301444608
49106,49107,-35.9294,-5.05959,702.5,9,4,1,63055067707604992
49137,49138,-122.0770,-17.91250,698.0,9,4,3,860203196868460544
49138,49139,-126.4970,-11.46120,698.0,9,4,3,49542963155435520
49140,49141,-151.8170,-17.51750,698.0,9,4,3,702565665038401536
49141,49142,-140.1300,-13.31260,698.0,9,4,3,598981636658298880
49142,49143,-163.7340,-30.38740,698.0,9,4,3,702566283513692160
49143,49144,-130.3760,-12.20430,698.0,9,4,3,333267334498091008
49144,49145,-134.9950,-25.67160,698.0,9,4,3,391821620076871680
49145,49146,-139.4550,-17.61050,698.0,9,4,3,157626261835874304
49158,49159,-35.6864,-5.04522,698.0,9,4,4,63055067707604992
49163,49164,-58.8014,-8.33213,698.0,9,4,4,873709941301444608
49192,49193,-41.6510,-17.78980,698.0,9,4,4,103593374228938752
49194,49195,-51.3988,-16.22200,698.0,9,4,4,707069951860539392
50051,50052,51.2592,-99.44180,698.0,9,4,35,94586724730011648
50078,50079,39.0981,-54.37640,698.0,9,4,36,711568947282968576
50122,50123,81.0019,-111.39200,698.0,9,4,38,324259379329105920
50270,50271,47.7848,-28.02180,702.5,9,4,44,585468157716594688
50340,50341,47.4497,-27.85340,698.0,9,4,47,585468157716594688
52200,52201,-145.0330,-17.47990,818.0,9,6,3,860203196868460544
52202,52203,-158.2800,-28.16240,818.0,9,6,3,391821620076871680
52206,52207,-163.2240,-23.45030,818.0,9,6,3,157626261835874304
52255,52256,-59.9014,-19.60030,818.0,9,6,4,707069951860539392
52260,52261,-41.8093,-6.20667,818.0,9,6,4,63055067707604992
52273,52274,-68.7487,-8.70239,818.0,9,6,4,873709941301444608
53097,53098,58.5190,-117.24500,818.0,9,6,35,94586724730011648
53106,53107,45.5882,-63.81900,818.0,9,6,36,711568947282968576
53161,53162,96.8054,-128.79900,818.0,9,6,38,324259379329105920
57774,57775,-55.9311,-9.39135,1098.0,9,10,4,63055067707604992
58375,58376,74.0233,-159.41500,1098.0,9,10,35,94586724730011648
58417,58418,60.3631,-85.86310,1098.0,9,10,38,711568947282968576
59897,59898,-108.0120,-7.57011,1298.0,9,12,3,873709941301444608
59918,59919,-66.0265,-11.91790,1298.0,9,12,4,63055067707604992
60457,60458,70.7264,-101.69900,1298.0,9,12,38,711568947282968576
61728,61729,-76.0205,-14.62570,1498.0,9,14,4,63055067707604992
61801,61802,-105.8080,-42.34490,1498.0,9,14,7,707069951860539392
62220,62221,80.9484,-117.50600,1498.0,9,14,38,711568947282968576
62322,62323,101.6750,-60.83080,1498.0,9,14,45,585468157716594688

In [64]:
layer_id_list =  list(set(dataset_3['layer_id']))
print(layer_id_list)

[2, 4, 6, 10, 12, 14]

In [67]:
particle_by_layer = dict()
for l in layer_id_list:
    d =  dataset_3[dataset_3['layer_id']==l]
    particle_by_layer[l] =  list(set(d['particle_id']))
    # print(set(dataset_3[dataset_3['particle_id'].isin(seclect)]
for k, v in particle_by_layer.items():
    print(k, len(v))

2 888
4 1176
6 868
10 683
12 594
14 516

In [71]:
import random
keys = list(particle_by_layer.keys())
smallest =  list(particle_by_layer[14])
select_particle_id = set()

for i in smallest:
    for k in keys[:-1]:
        if i in particle_by_layer[k]:
            select_particle_id.add(i)
select_particle_id =  list(select_particle_id)
idx = set()
while len(idx) < 10:
    idx.add(random.randint(0, len(select_particle_id)-1))
len(idx)

rand_particles = []
for i in idx:
    rand_particles.append(select_particle_id[i])
rand_particles

TypeError: 'set' object is not subscriptable